### ISSUE TITLE
Getting started documentation

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/docs.openfeature.dev#230]
## Overview

People interested in using OpenFeature need a basic end-to-end tutorial that explains how to use OpenFeature in any language with an SDK. 

## Requirements

- [x] [Getting started tutorial for JS](https://docs.openfeature.dev/docs/tutorials/getting-started/node)
- [x] [Getting started tutorial for Java](https://docs.openfeature.dev/docs/tutorials/getting-started/java)
- [ ] [Getting started tutorial for PHP](https://github.com/open-feature/docs.openfeature.dev/issues/206)
- [ ] [Getting started tutorial for Go](https://github.com/open-feature/docs.openfeature.dev/issues/208)
- [ ] [Getting started tutorial for .NET](https://github.com/open-feature/docs.openfeature.dev/issues/207)
